import Navbar from "@/components/navbar";
import { Text } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";

export const MainLayout = ({ children }: { children: any }) => {
  return (
    <>
      <Head>
        <title>My projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export const IndexLayout = ({ children }: { children: any }) => {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
};

export const SubLayout = ({ children }: { children: any }) => {
  return (
    <>
      <Text position="absolute" top="0" left="0" zIndex={5}>
        <Link href="/"> Back </Link>
      </Text>
      {children}
    </>
  );
};
