import Head from "next/head";
import { Box, Heading, Center } from "@chakra-ui/react";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ x: "-100%" }}
        animate={{ x: "0" }}
        exit={{ x: "-100%" }}
        transition={{ duration: 0.75, ease: "easeOut" }}
      >
        <Box as="main">
          <Center w="100%" h="100%">
            <Box>
              <Heading as="h1">Michal Špitálský</Heading>
              <Heading as="p">We can live in a world that we design</Heading>
            </Box>
          </Center>
        </Box>
      </motion.div>
    </>
  );
}
