import { Box, Heading, Center } from "@chakra-ui/react";
import { motion } from "framer-motion";
import Head from "next/head";

const ProjectsPage = () => {
  return (
    <>
      <Head>
        <title>My projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ x: "100%" }}
        animate={{ x: "0%" }}
        exit={{ x: "100%" }}
        transition={{ duration: 0.75, ease: "easeOut" }}
      >
        <Box as="main" bgColor="#48bf84" color="white">
          <Center w="100%" h="100%">
            <Box>
              <Heading as="h1">Projects</Heading>
            </Box>
          </Center>
        </Box>
      </motion.div>
    </>
  );
};

export default ProjectsPage;
