import Head from "next/head";
import { motion } from "framer-motion";
import { Box, Heading, Text, Badge } from "@chakra-ui/react";
import { projects } from "@/data/projects";

const ProjectsPage = () => {
  return (
    <>
      <Head>
        <title>My projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ x: "100%" }}
        animate={{ x: "0%" }}
        exit={{ x: "100%" }}
        transition={{ duration: 0.75, ease: "easeOut" }}
      >
        <Box as="main" bgColor="#48bf84" color="white">
          <Heading as="h1">Projects</Heading>
          {projects.map((project) => (
            <>
              <Heading
                as="h2"
                key={project.name}
                fontFamily="Gilroy Heavy"
                textTransform="lowercase"
                fontSize="6xl"
                lineHeight="5xl"
                letterSpacing="-1px"
              >
                {project.name}{" "}
                <Text as="span" fontSize="2xl" letterSpacing="5px">
                  {project.type}
                </Text>
              </Heading>
            </>
          ))}
        </Box>
      </motion.div>
    </>
  );
};

export default ProjectsPage;
